sudo: required

language: node_js
node_js:
  - "10"
  - "12"
  - "node"
services:
  - mysql
before_install:
  - cp .env.dist .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS polymorphic;'
  - npm i -g npm@latest
  - npm i -g yarn
install:
  - yarn
script:
  - yarn run test
after_success: yarn run coveralls
